name: prettier
on: [push, pull_request]
jobs:
  prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install -D
      - name: Check formatting
        run: npx prettier --check "**/*.{yml,yaml}"
